### ISSUE TITLE
Parent still appearing in the parent management modal and the manage values over time windows while inactive for the selected date

### ISSUE THREAD

**Issue by SteeveEbener** [terraframe/geoprism-registry#495]
**List the CGR information**
- CGR version: 0.12.2
- CGR instance (e.g. a URL): Staging

**Describe the bug (clear and concise)**
The parent is still appearing in the parent management modal and the manage values over time windows while such parent is inactive for the selected date

**To Reproduce**
As a RA/RM of the organization having the curation mandate over the administrative divisions
1. Go to the lists module
2.  Open the list for the admin level to which health facilities are attached to (Shire in Tolkien)
3. Inactivate one of the Shire from a given date (Shire TLK0102038 from 2007-04-20 in Tolkien)
4. Log out as MOHA RA/RM and log in as MOH RA/RM
5. Go to the lists module and view at the 2020-07-06 list of health centers (refresh)
6. See that for record HF0171 there is not Shire Parent
7. Click the edit pen button for that record
8. Click the parents tab
9. See the first error: the Shire of Talongog (TLK0102038) is still appearing in the window (first screenshot below)
10. Click the edit button for the Health geography hierarchy (MOH) hierarchy
11. See the second error: the Shire of Talongog (TLK0102038) is appearing as an active parent form Jan 1, 2020 to the future while it is inactive since 2007-04-20 (second screenshot below)
12. Create a new instance for the Shire parent with a start date after 2007-04-20
13. See the third error: the Shire of Talongog (TLK0102038) is appearing as one of the options while inactive since 2007-04-20

**Expected behavior (clear and concise)**

- The field containing the parent should be empty in both the list view, the Parent management modal and the manage values over time windows for dates after the inactivation of the Shire
- The inactivated Shire should not appear in the list of options you can assign for an instance valid after 2007-04-20 
- Ideally, the end date for the first instance should automatically be set to 2007-04-20 and a new empty instance starting from this date automatically added to the view
- The fact that this Shire does not exist anymore since 2007-04-20 should have been flagged to the RA/RM having the curation mandate over the master list of health centers for her/him to fill this information

**Screenshots**
![](https://user-images.githubusercontent.com/12602163/102421165-c314c380-403e-11eb-8b05-9eaf0baf2b85.png)

![](https://user-images.githubusercontent.com/12602163/102421231-e5a6dc80-403e-11eb-9bd3-81746b19a30c.png)

![](https://user-images.githubusercontent.com/12602163/102421443-606ff780-403f-11eb-806e-c888ae33a980.png)

**Desktop (please complete the following information):**
 - OS:  Windows 10
 - Browser: Google Chrome
 - Version: Version 87.0.4280.88 (Official Build) (64-bit)

**Additional context (if any)**
- See ticket #239 for more information about the case
- This is an excellent illustration of the importance of the curation module. .

**Comment by rrowlands** [comment]
1. Due to the age of this ticket, it now has an issue with terminology. Invalid / valid does not have a time component. I will assume that whenever this ticket is mentioning invalid / valid it is actually referring to existence.
2. I cannot reproduce your third error. I believe this issue was fixed when we implemented the Change Request additions. If the parent Geo-Object either does not exist in the specified time range or is invalid it does not appear in the autocomplete picker for parents.
3. If the existence or validity of the parent changes, the best we can do is display an error message when viewing the child Geo-Object. I will implement this feature for this ticket.

**Comment by SteeveEbener** [comment]
1. Correct. I have adjusted the terminology in the ticket. Thanks for noticing this
2. The issue for the third error is still there as per the following screenshot (Talongog is still appearing as an option when creating a new instance of parents for a period over which this Shire does not exist):
![image](https://user-images.githubusercontent.com/12602163/145129459-0e3bbc45-786c-425b-8905-f1511003bb63.png)
3. I did not get it, where would such an error message be displayed and what would be its content?

**Comment by SteeveEbener** [comment]
Thanks Richard. If I understand correctly the parent would then have to be changed manually but there is no way that the value would actually be automatically set to "Null"?  I am asking because it is confusing to see the warning message while there is actually a parent that is appearing in the corresponding fields. 

Should the first warning message not read "Parent does not exist **for** this time range" instead of "Parent does not exist at this time range"?

**Comment by justinlewis** [comment]
Closing legacy issues created under a prior funded development effort. These items were associated with a separate roadmap and stakeholder group targeting the v 1.x release. Archiving these tickets enables a v 2 reset of the backlog. All of these tickets can be found by searching for the geoprism-v1-archive tag on tickets. If any issue remains relevant to current priorities, please reopen or ideally create a new issue referencing this thread.
