### ISSUE TITLE
Lat/Long attributes not appearing anymore in the lists for points format geo-object types

### ISSUE THREAD

**Issue by SteeveEbener** [terraframe/geoprism-registry#569]
**List the CGR information**
- CGR version: 0.13.4
- CGR instance (e.g. a URL): Production

**Describe the bug (clear and concise)**
The lat/Long attributes are not appearing anymore in the lists for points format geo-object types

**To Reproduce**
As a any role
1. Go to the lists module
2. View the list for a point format geo-object type (villages for example
3. See error: the lat/long attributes are not appearing in the list anymore (they are not in the exported file as well)

**Expected behavior (clear and concise)**
The lat/long attributes are included in the list

**Screenshots**

**Desktop (please complete the following information):**
 - OS: Windows 10
 - Browser: Google Chrome
 - Version: the latest one

**Additional context (if any)**

**Comment by justinlewis** [comment]
@steeveebener Just to be clear are you sure these columns appeared in these exact lists in the past?  

I ask because the lat / long fields should only have ever showed up in lists where the Geo-Object geometry type is Point (not multi-point). Since we change all geometry types to multi-part features this should never happen anymore. The reason you saw lat / long in those single-point lits was because we would get the lat / long from the database when rendering the table BUT multi point isn't displayed as simple lat / long columns. That would require a format like Well Known Text or GeoJSON. So the only way currently to show the lat / long values of a spreadsheet is to create custom attributes on the Geo-Object Type and import them as their own attributes.

**Comment by SteeveEbener** [comment]
@justinlewis . I can't remember how far back they were appearing but it can indeed be when we were differentiating between the single vs multiple geometry

=> lat/long should appear in the list when the geometry type is set to single-point

=> I guess this means we need to address ticket #353 at the same time

**Comment by justinlewis** [comment]
We had agreed that a quick an easy solution is to add a checkbox to the masterlist metadata which, when checked, would add lat and long columns (after the list is refreshed). This checkbox will only be available for GeoObjectTypes who's geometry type is point. For Geo-Objects that have more than one point, the first point will be picked.

**Comment by SteeveEbener** [comment]
Few comments/questions regarding what has been agreed upon on your side:

1. In which metadata do you plan to include this check box? the one for the list or the one for the spatial data? => I would argue that this should be in the one for the spatial data
2. The RA/RM should be able to check the checkbox for both public and private spatial data but the lat/long column would only appear to outside organization if the spatial data is public
3. How are we going to deal with the attributes that can be associated to the lat/long? I am thinking about the coordinates source or the accuracy measure. It would be strange if the lat/long are not in the list (private) while the other information are (linked to ticket 431)
4. I don't think that "For Geo-Objects that have more than one point, the first point will be picked" is a good approach. It was my understanding that the CGR can’t handle multipoints. If it is now possible then we first need to solve ticket #353. Once this is done the possibility to display lat/long in the list would only be possible if we are dealing with “single points”.

**Comment by rfromthecastle** [comment]
I think this is fixed in v0.19, right?

**Comment by justinlewis** [comment]
Yep you're correct. Thanks for the catch.

**Comment by SteeveEbener** [comment]
There is now indeed a check box in the configuration window to define if you want the lat/long to be displayed in the list or not. After testing:
- Checking or not this box at the time of creating a new set works 
- Unchecking this box after the set has been created (which is possible) does not work, meaning that the lat/long are still appearing in the list and shape file (once exported)
- Re-checking this box after having unchecked it generates the following error message (the box nevertheless appears checked after closing and re-opening the configuration window):
![image](https://user-images.githubusercontent.com/12602163/181661935-0020be29-4aac-4911-af09-ec7e9741aeb3.png)

=> This is still not fully operational

Once the above has been fixed, the implementation will address point 1 from my message dated Dec 15, 2021 and I will be able to close this ticket as:
- Points 2, and to some extent point 3, should themselves be managed at the geo-object type level => captured in ticket #431 
- point 4 is to be handled in ticket #353

**Comment by SteeveEbener** [comment]
Just checked the issue reported in my comment dated Jul 29th on staging and the same problem persists with the only difference that after re-checking the "include latitude and longitude" option in the configuration file the error message does not appear anymore.

=> unchecking that box does not remove the lat/long from the list

**Comment by rrowlands** [comment]
Just talked with @jsmethie, apparently the "Include Latitude and Longitude" as well as the parent checkboxes were never intended to be editable in this dialog. They cannot be changed after your List Type is defined. I have removed the ability to edit these fields, as well as fixed some minor styling issues as e26d8f5a07cfe205ddc95fcc5b53194a81afe011.

**Comment by SteeveEbener** [comment]
Thanks. Please let me know when this is available on staging

**Comment by rfromthecastle** [comment]
Fix working on Staging

**Comment by SteeveEbener** [comment]
Tested under Version: 1.0.1 (2023-02-24T21:25:54Z) and indeed working. It is just a bit strange that when you uncheck this box you actually can't also hide the other data elements related to the lat/long (Source geographic coordinates for Village (MOHA)) for example.

This being said, this is a functionality that has not yet been discussed and could very much apply to all the data elements.

=> I am closing this ticket
